---
# ***** U.S. SECURITY CLASSIFICATION: UNCLASSIFIED ***************************
# ***** U.S. EXPORT CONTROL CLASSIFICATION NUMBER (ECCN): EAR99 **************
#
# Common Software Factory Pipeline Template
#
# Copyright 2019-2023 - Lockheed Martin Corporation.
#
# For U.S. Government Users: The Government is granted Unlimited Rights in
# this pipeline template as defined in DFARS 252.227-7013 (a)(16) and
# 252.227-7014 (a)(16). The Government has the right to use, modify,
# reproduce, perform, display, release or disclose this computer software
# in whole or in part, in any manner, and for any purpose whatsoever,
# and to have or authorize others to do so.
#
# For All Other Users: This pipeline template contains Lockheed Martin
# Proprietary Information. If delivered under a contract, use of this pipeline
# template is subject to the terms of use as required by the contract under
# which it was delivered.  No other use is permitted without the prior written
# authorization of Lockheed Martin Corporation.
#
# For All Users: The classification, ECCN, and license terms in this file
# apply solely to this file. Software built or assembled by this pipeline
# template may be subject other licensing terms or other restrictions on use
# (e.g. export control). The recipient/user should check the markings on each
# item/software provided to ensure use consistent with its restrictions.
# ****************************** UNCLASSIFIED ********************************
#
# CI Jobs for sigstore-helm-charts repo
#
# version: {{version}}

#############################################################################################################
# This workflow definition is intended to prevent duplicate branch and MR pipelines running - one is plenty
#############################################################################################################
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
    - if: "$CI_COMMIT_BRANCH"

#############################################################################################################
# Remote and local included pipeline templates
#############################################################################################################
include:
  - remote: "https://pipeline-catalog.global.lmco.com/api/v1/modules/stages/v1.0.10/templates/stages.gitlab-ci.yml"
  - remote: "https://pipeline-catalog.global.lmco.com/api/v1/global/modules/java-maven/v6.2.46/modules/maven-build.yml"
  # - remote: "https://pipeline-catalog.global.lmco.com/api/v1/global/modules/kaniko/v3.0.23/modules/kaniko-build.gitlab-ci.yml"
  # - remote: "https://pipeline-catalog.global.lmco.com/api/v1/global/modules/crane/v4.1.1/modules/crane_copy.yml"
#############################################################################################################
# Variables
#############################################################################################################

variables:
    http_proxy: http://proxy-zsgov.external.lmco.com:80
    https_proxy: http://proxy-zsgov.external.lmco.com:80
    no_proxy: ".lmco.com,.LMCO.COM,*.lmco.com,*.LMCO.COM,127.0.0.1,localhost,.amazonaws.com,*.amazonaws.com"
#############################################################################################################
  # Maven Variable
#########################################
    MAVEN_RELATIVE_SOURCE_DIRECTORY: "."
    ENABLE_MVN_SITE: "false"
    MAVEN_TAG: "3.8.6-openjdk-11"
    ENABLE_MVN_BUILD: "true"
#########################################
#    # Crane Destination Variables
# #########################################
#     CRANE_DESTINATION_IMAGE: registry.gitlab.global.lmco.com:443/software-factory/applications/secure-delivery/secure-software-supply-chain-tools/hyades/hyades-api-server
#     CRANE_DESTINATION_IMAGE_TAG: $CI_COMMIT_REF_NAME
#     CRANE_DESTINATION_REGISTRY: registry.gitlab.global.lmco.com:443
#     CRANE_DESTINATION_REGISTRY_USER: gitlab-ci-token
#     CRANE_DESTINATION_REGISTRY_PASSWORD: $GITLAB_API_TOKEN
# #########################################
#     # Kaniko Variables
# #########################################
#     DOCKER_BUILD_DIR: "./src/main/docker"
#     DOCKER_IMAGE: $CRANE_DESTINATION_IMAGE
#     DOCKER_REGISTRY: $CRANE_DESTINATION_REGISTRY
#     DOCKER_IMAGE_NAME_TAGGED: $CRANE_DESTINATION_IMAGE_TAG
#     ENABLE_KANIKO: "true"
#     KANIKO_BOM_GEN: "false"
# #############################################################################################################

# ## Java Build with Maven
# #############################################################################################################
# mvn_build:
#     image: $MAVEN_IMAGE:$MAVEN_TAG
#     stage: build
#     artifacts:
#         paths:
#             - $MAVEN_RELATIVE_SOURCE_DIRECTORY/target/
# #############################################################################################################
# # Kaniko Section
# #############################################################################################################
# kaniko:
#   stage: package
#   rules:
#     - if: $ENABLE_KANIKO == "true"

# # Had to move this to package stage despite being disabled by KANIKO_BOM_GEN variable
# kaniko-bom:
#   stage: package

# # Had to move this to package stage despite being disabled by KANIKO_BOM_GEN variable
# kaniko-bom-validate:
#   stage: package

